#!/usr/bin/python3
def MCD(a, b):
    if a == 0:
        return b, 0, 1
    mcd, U, V = MCD(b % a, a)
    u = V - (b // a) * U
    v = U
    return mcd, u, v

p = int(input("Num 1: "))
q = int(input("Num 2: "))

mcd, u, v = MCD(p, q)

if mcd==1:
  print(f"Los numeros {p} y {q} son primos relativos. Su mcd es de {mcd}")
else:
  print(f"Los numeros {p} y {q} NO son primos relativos. Su mcd es de {mcd}")
